### PR TITLE
load readme as utf8

### LINKED ISSUE #36: UnicodeDecodeError during install
Got the following error when trying to pip install:

```
Step 13 : RUN pip3 install -r requirements.txt
 ---> Running in 88308c270095
Collecting docker-py==1.7.0 (from -r requirements.txt (line 1))
  Downloading docker_py-1.7.0-py2.py3-none-any.whl
Collecting spur==0.3.15 (from -r requirements.txt (line 2))
  Downloading spur-0.3.15.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-t6r3jpgx/spur/setup.py", line 13, in <module>
        long_description=read("README.rst"),
      File "/tmp/pip-build-t6r3jpgx/spur/setup.py", line 7, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
      File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3190: ordinal not in range(128)
```

Perhaps we need to set the encoding when opening the file?

### PR DESCRIPTION
**Pull request by zbyte64**
Fix #36

### CODE REVIEW

**Comment by mwilliamson** [comment]
I don't think `open` on Python 2 supports the `encoding` argument, does it?

**Comment by zbyte64** [comment]
Blast, you are correct. Maybe codes.open instead?

https://docs.python.org/2/library/codecs.html#codecs.open

**Comment by mwilliamson** [comment]
I think `io.open` is probably more appropriate, since that's what `open` is on Python 3.

**Comment by mwilliamson** [comment]
I'm still confused by why you're getting the error in the first place. So far as I can tell `README.rst` doesn't contain any non-ASCII characters.

Does tox pass on all platforms with the change?

**Comment by mwilliamson** [comment]
Removed the non-ASCII character from `README.rst`. Let me know if I missed any, or if there are any other issues.

**Pull request closed without merging**
